# shard_deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shard-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shard
  template:
    metadata:
      labels:
        app: shard
    spec:
      containers:
      - name: shard
        image: shard-image:latest
        ports:
        - containerPort: 8080
